[theme]
base = "light"
primaryColor = "#32FF69"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#1A1A1A"
font = "sans serif"

[server]
maxUploadSize = 200

enableXsrfProtection = true

[browser]
gatherUsageStats = false
